S3 us02/login page
WildCodeSchool-2024-02/toulouse-babyplace pull request #19
Opened 2024-06-18 15:29 UTC by magicbob31

2024-06-18 15:29 UTC, RomainRG31 approved these changes
Impeccable !

2024-06-18 15:31 UTC, ArthurHtbk requested changes
"/signuppro" => "/sign-up-pro"

2024-06-19 07:39 UTC, ileanaspl approved these changes

2024-06-19 08:07 UTC, ArthurHtbk requested changes
médiaQ => mediaQ

2024-06-19 08:10 UTC, ileanaspl approved these changes

2024-06-19 08:11 UTC, ArthurHtbk approved these changes

2024-06-19 08:11 UTC, merged